### ISSUE TITLE
Desarrollo del Gantt de proyecto integrador 

### ISSUE THREAD

**Issue by israel38** [israel38/Proyecto_Integrador#13]

**Comment by israel38** [comment]
Desarrollo del Gantt de trabajo

**Comment by Maucare12** [comment]
Gant en desarrollo

**Comment by Maucare12** [comment]
Se sube al proyecto el día Lunes 14 de Octubre

**Comment by Maucare12** [comment]
Se sube Rev1 del Gantt.
Se subirá una Rev 2 una vez finalizado por completo el proyecto.
