### ISSUE TITLE
Realizar el documento del estandar de identificacion

### ISSUE THREAD

**Issue by israel38** [israel38/Proyecto_Integrador#32]
El docuemnto debe contener la reglas de la identificacion de la variables a utilizar en el programa.

El documento debe estar cargado dentro del repositorio en la siguiente direccion y con el siguinete nombre:

Proyecto Integrador\3) Design\9.2. NamingConventions_AAAMMDD.docx

**Comment by SWRoberto** [comment]
Documento creado e incluido
