### ISSUE TITLE
Realizar el documento de Integration Test Strategy

### ISSUE THREAD

**Issue by israel38** [israel38/Proyecto_Integrador#33]
Cada ves que un modulo es implentando , cada prueba debe contener uan refrencia a el nuemro de requerimiento para tener trazabilidad.
El documento debe ser guardado en la siguiente direccion  Proyecto_Integrador\4) Verification\Results\

**Comment by Maucare12** [comment]
Se utiliza Integración ascendente

**Comment by Maucare12** [comment]
Se actualiza el SDP donde se habla de esta sección

**Comment by Maucare12** [comment]
Se actualiza baseline y results
